version: '3.8'

networks:
  dev:
    driver: bridge

services:
  catebi_api:
    image: catebi_api:latest
    volumes:
      - /etc/letsencrypt/live/api.catebi.ge/fullchain.pem:/app/certs/cert.pem
      - /etc/letsencrypt/live/api.catebi.ge/privkey.pem:/app/certs/privkey.pem
    platform: linux/amd64
    depends_on:
      - catebi_db
    container_name: catebi_api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ci/docker/Dockerfile.catebi.api
    environment:
      - ConnectionStrings__Pgsql=Host=catebi_db;Port=5432;Database=catebi;Username=catebi_app;Password=${CATEBI_APP_DB_PASS};Include Error Detail=True;
      - VersionInfo__Version=${VERSION}
      - VersionInfo__Build=${BUILD}
      - AdoptionBot__Telegram__Token=${ADOPTIONBOT_TELEGRAM_TOKEN}
      - AdoptionBot__Telegram__CommonBotToken=${ADOPTIONBOT_COMMON_BOT_TOKEN}
      - AdoptionBot__Airtable__ApiKey=${ADOPTIONBOT_AIRTABLE_APIKEY}
      - AdoptionBot__Airtable__BaseId=${ADOPTIONBOT_AIRTABLE_BASEID}
      - Finance__Tribute__ApiKey=${FINANCE_TRIBUTE_APIKEY}
      - Finance__Telegram__SuperchatId=${CATEBI_TELEGRAM_SUPERCHAT_ID}
      - Finance__Telegram__TopicId=${CATEBI_FINANCE_TELEGRAM_TOPIC_ID}
      - Finance__Airtable__ApiKey=${FINANCE_AIRTABLE_APIKEY}
      - Finance__Airtable__BaseId=${FINANCE_AIRTABLE_BASEID}
      - Cors__AllowedOrigins=${CORS_ALLOWED_ORIGINS}
    networks:
      - dev

  catebi_db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - dev

  backups:
    image: prodrigestivill/postgres-backup-local:16-debian-4d1f860
    restart: always
    depends_on:
      - catebi_db
    networks:
      - dev
    volumes:
      - /var/opt/pgbackups:/backups
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=catebi
      - POSTGRES_USER=catebi_app
      - POSTGRES_PASSWORD=${CATEBI_APP_DB_PASS}
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6

volumes:
  postgres-data:
