version: '3.4'

networks:
  dev:
    driver: bridge

services:
  catebi_api:
    image: catebi_api:latest
    platform: linux/amd64
    depends_on:
      - catebi_db
    container_name: catebi_api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ci/docker/Dockerfile.catebi.api
    environment:
      - ConnectionStrings__Pgsql=Host=catebi_db;Port=5432;Database=catebi;Username=catebi_app;Password=password;Include Error Detail=True;
      - NotionApi__AuthToken=notion_auth_toket
      - NotionApi__DatabaseIds__Cats=catdb_id
      - NotionApi__DatabaseIds__Volunteers=volunteerdb_id
    networks:
      - dev

  catebi_db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - dev

  backups:
    image: prodrigestivill/postgres-backup-local:16-debian-4d1f860
    restart: always
    depends_on:
      - catebi_db
    networks:
      - dev
    volumes:
      - /var/opt/pgbackups:/backups
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=catebi
      - POSTGRES_USER=catebi_app
      - POSTGRES_PASSWORD=password
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6

volumes:
  postgres-data:
