name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      # Install dotnet format as a global tool
      - name: Install dotnet tools
        run: dotnet tool restore

      - name: Run Linter
        run: |
          sudo chmod +x ./.github/scripts/check.sh
          ./.github/scripts/check.sh
        shell: bash

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --filter "FullyQualifiedName~Notion.UnitTests" --no-build --verbosity normal
