# https://github.com/dotnet/dotnet-docker/issues/4388
# https://github.com/dotnet/dotnet-docker/tree/main/samples/aspnetapp

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS dotnet-build
LABEL "Author" = "sasha.karpov@catebi.team"
ARG TARGETARCH
WORKDIR /src

COPY . .

# Step 1: restore .net dependencies
RUN case "$TARGETARCH" in \
          amd64) DOTNET_RID="linux-musl-x64" ;; \
          arm64) DOTNET_RID="linux-musl-arm64" ;; \
          *) echo "Unsupported TARGETARCH=$TARGETARCH" && exit 1 ;; \
        esac && \
        dotnet restore \
          --configfile "./nuget.build.config" \
          -r "$DOTNET_RID" \
          /p:PublishReadyToRun=true \
          Catebi.Api.sln \
          /m:1 /nr:false \
          /p:UseSharedCompilation=false

# Step 2: build and publish
WORKDIR /src
RUN case "$TARGETARCH" in \
          amd64) DOTNET_RID="linux-musl-x64" ;; \
          arm64) DOTNET_RID="linux-musl-arm64" ;; \
          *) echo "Unsupported TARGETARCH=$TARGETARCH" && exit 1 ;; \
        esac && \
    dotnet publish Catebi.Api/Catebi.Api.csproj -c Release -o /app/publish \
      -r "$DOTNET_RID" \
      --no-restore \
      --self-contained false \
      /p:RunAnalyzers=false \
      /m:1 /nr:false \
      /p:UseSharedCompilation=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine as base
WORKDIR /app

# Step 3: upgrade musl
RUN apk add --no-cache icu-libs \
  && apk upgrade musl \
  && adduser --disabled-password \
    --home /app \
    --gecos '' dotnetuser && chown -R dotnetuser /app

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
EXPOSE 8080

USER dotnetuser

# Step 4: prepare final image
FROM base AS final
WORKDIR /app
COPY --from=dotnet-build  /app/publish .

ENTRYPOINT ["./Catebi.Api"]
