name: Build and Deploy to VPS

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Version Info
      run: |
        echo "COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV
        echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
        echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV

    - name: Setup SSH and SCP files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          mkdir -p ~/Catebi.Api
          rm -rf ~/Catebi.Api/*

    - name: Copy source and Docker configs
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "."
        target: "~/Catebi.Api"

    - name: Build and deploy using Docker on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/Catebi.Api
          echo "VERSION=0.0.0-${{env.BRANCH_NAME}}-${{ env.GITHUB_RUN_NUMBER }}" > .env
          echo "BUILD=${{ env.COMMIT_SHA }}" >> .env
          echo "CATEBI_APP_DB_PASS=${{ secrets.CATEBI_APP_DB_PASS }}" >> .env
          echo "POSTGRES_DB_PASS=${{ secrets.POSTGRES_DB_PASS }}" >> .env
          echo "ADOPTIONBOT_TELEGRAM_TOKEN=${{ secrets.ADOPTIONBOT_TELEGRAM_TOKEN }}" >> .env
          echo "ADOPTIONBOT_AIRTABLE_APIKEY=${{ secrets.ADOPTIONBOT_AIRTABLE_APIKEY }}" >> .env
          echo "ADOPTIONBOT_AIRTABLE_BASEID=${{ secrets.ADOPTIONBOT_AIRTABLE_BASEID }}" >> .env
          docker-compose down
          docker-compose up --build -d
